[package]
name = "coretools_rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.4.2", features = ["derive"] }
thiserror = "1.0.47"
zip = "0.6.6"
walkdir = "2.3.3"